### ISSUE TITLE
使用文档不详细，建议加上如下说明

### ISSUE THREAD

**Issue by keehao** [huangdijia/laravel-ssdb#4]
1、config\app.php的节点 'providers' 添加 一行配置
Huangdijia\Ssdb\SsdbServiceProvider::class,

2、config\database.php根节点添加配置
 'ssdb' => [
        'default' => 'default',
        'connections' => [
            'default' => [
                'host' => env('SSDB_HOST', '127.0.0.1'),
                'port' => env('SSDB_PORT', 8888),
                'timeout' => env('SSDB_TIMEOUT', 2000),
                'password' => env('SSDB_PASSWORD', ''), // optional
            ],
        ],
    ],

3、使用
use Huangdijia\Ssdb\Facades\Ssdb;

Ssdb::set('key', time());
$value = Ssdb::get('key');
var_dump($value);

**Comment by huangdijia** [comment]
laravel 有服务自动发现，不需要手动添加ServiceProvider啊
